INSERT INTO projects(pid, title, class, daterange)
VALUES
(1, 'Syetem Design of a Search Engine', 'EECS 398 - 001 (MDE)', 'Upcoming'),
(2,  'This Website', 'Personal Project', 'Ongoing'),
(20, 'Py-Time-Slice', 'Personal Project', 'May 2019'),
(21, 'Computer Forensics', 'EECS 388: Computer Security', 'April 2019'),
(22, 'Wikipedia Search Engine', 'EECS 485: Web Systems', 'April 2019'),
(23, 'Application Security', 'EECS 388: Computer Security', 'March 2019'),
(24, 'Networking and Web Secuirty', 'EECS 388: Computer Security', 'March 2019'),
(25, 'Instagram Clone', 'EECS 485: Web Security', 'February 2019'),
(26, 'Database Design', 'EECS 484: Database Management Systems', 'December 2018'),
(27, 'Citizen Science for the Dark Energy Survey', 'Undergraduate Research', 'May 2018'),
(28, 'Traveling Salesman Problem', 'EECS 281: Data Structures and Algorithms', 'December 2017'),
(29, 'Computer Architecture', 'EECS 370: Introduction to Computer Organization', 'December 2017'),
(30, 'Stock Market Simulation', 'EECS 281: Data Structures and Algorithms', 'November 2017');

INSERT INTO project_action_points(apid, proj_id, bp)
VALUES
(1, 26, 'Build and queried databases using SQL, Java, and MongoDB'),
(2, 26, 'Linear Hashing Index, External Merge Sort, and Grace Hash Join implementations'),
(3, 28, 'Minimum Spanning Tree implementations using Prim’s and Kruskal’s Algorithms'),
(4, 28, 'Approximations using a nearest neighbor algorithm and 2-opt'),
(5, 28, 'Optimal solution implementation using a branch and bound algorithm'),
(6, 29, 'Implemented an assembler, CPU simulator (single-cycle and pipeline), cache simulator'),
(7, 29, 'Translated functions to assembly including integer multiplication and a recursive combination formula'),
(8, 30, 'Implemented a Hash Table and Priority Queue'),
(9, 30, 'Further experience with Stacks, Queues, Pairing Heaps, templated classes'),
(10, 1, 'A semester long project to build a search engine in a group of 6+ students. Details to come...'),
(11, 21, 'Analyze a hard drive and hidden communication networks to determine whether a disgruntled ex-employee''s actions were illegal'),
(12, 21, 'Used live and dead analysis of the hard drive, password crackers, SQL injections, steganalysis, and social engineering to gather evidence'),
(13, 22, 'Search all of Wikipedia with a search engine built off of the hadoop MapReduce pipeline, PageRank scores, and tf-idf scores'),
(14, 22, 'Includes an optional PageRank/tf-idf score weight slider to control the weight of each factor'),
(15, 23, 'Used buffer overflow attacks and ROP gadgets to hijack control of vulnerable programs'),
(16, 23, 'Overwrote return addresses and opened a root shell in simple situations, with DEP enabled, and with variable stack positions'),
(17, 24, 'Used SQL Injections, Cross Site Scripting (XSS), and Cross Site Request Forgery (CSRF) to attack vulnerable websites and gain access to protected data'),
(18, 24, 'Analyzed web traffic with Wireshark to locate vulnerabilities.'),
(19, 25, '3-part project consisting of a static site, server-side dynamic site, and client-side dynamic site all of which are rudamentary copies of Instagram'),
(20, 25, 'Can create or delete users, posts, comments, and likes'),
(21, 25, 'Built using python, flask, jinja2, and sqlite'),
(22, 27, 'Independently programmed image analysis and editing programs to improve photos from cosmological surveys'),
(23, 27, 'Lead image manipulation efforts by filtering images to isolate and enhance the most useful data'),
(24, 20, 'Created a python program to combine a series of hundreds of timelapse images into one composite image'),
(25, 20, 'Built a GUI to make it more user-friendly and handle errors in a better way'),
(26, 20, 'Fully functional and optimized accross a variety of different options'),
(27, 2, 'Development on this website began in March 2019'),
(28, 2, 'Right now this is a server-side dynamic, templated website running a sqlite database');

INSERT INTO project_links(plid, proj_id, link, link_type)
VALUES
(1, 20, '/static/videos/pytimeslice.mp4', 'video'),
(2, 2, 'https://github.com/abschmidt6/personal-website', 'github'),
(3, 20, 'https://github.com/abschmidt6/py-time-slice', 'github');


INSERT INTO photography_places(pid, filename, location, description, date_taken, places_group)
VALUES
(NULL, '', 'Venice, Italy', 'Venetian Street Scene', '', 'Venice and the Balkans'),
(NULL, '', 'Venice, Italy', 'St. Mark''s Square', '', 'Venice and the Balkans'),
(NULL, '', 'Venice, Italy', 'Chruch of San Giorgio Maggiore', '', 'Venice and the Balkans'),
(NULL, '', 'Venice, Italy', 'Gondolas From St. Mark''s Square', '', 'Venice and the Balkans'),
(NULL, '', 'Venice, Italy', 'Gondola Station', '', 'Venice and the Balkans'),
(NULL, '', 'Venice, Italy', 'The Grand Canal at Sunset', '', 'Venice and the Balkans'),
(NULL, '', 'Pula, Croatia', 'Pula Ampitheatre', '', 'Venice and the Balkans'),
(NULL, '', 'Starigrad, Croatia', 'A Small Beachy in a Small Town', '', 'Venice and the Balkans'),
(NULL, '', 'Zadar, Croatia', 'Fisherman in Zadar', '', 'Venice and the Balkans'),
(NULL, '', 'Plitvicka Jezera, Croatia', 'Plitvice Lakes National Park', '', 'Venice and the Balkans'),
(NULL, '', 'Plitvicka Jezera, Croatia', 'Sunset at Plitvice Lakes', '', 'Venice and the Balkans'),
(NULL, '', 'Plitvicka Jezera, Croatia', 'Waterfalls at Plitvice Lakes', '', 'Venice and the Balkans'),
(NULL, '', 'Josan, Croatia', 'Croatian Milky Way', '', 'Venice and the Balkans'),
(NULL, '', 'Sibenik, Croatia', 'Coastline', '', 'Venice and the Balkans'),
(NULL, '', 'Sibenik, Croatia', 'Buoys', '', 'Venice and the Balkans'),
(NULL, '', 'Split, Croatia', 'Split From the Sea', '', 'Venice and the Balkans'),
(NULL, '', 'Split, Croatia', 'Diocletian''s Palace', '', 'Venice and the Balkans'),
(NULL, '', 'Split, Croatia', 'Split at Night', '', 'Venice and the Balkans'),
(NULL, '', 'Hvar, Croatia', 'Hvar Town', '', 'Venice and the Balkans'),
(NULL, '', 'Omis, Croatia', 'Omis', '', 'Venice and the Balkans'),
(NULL, '', 'Makarska, Croatia', 'Makarska', '', 'Venice and the Balkans'),
(NULL, '', 'Mostar, Bosnia and Herzegovinia', 'Mostar', '', 'Venice and the Balkans'),
(NULL, '', 'Dubrovnik, Croatia', 'Dubrovnik', '', 'Venice and the Balkans'),
(NULL, '', 'Dubrovnik, Croatia', 'Dubrovnik Cable Car', '', 'Venice and the Balkans'),
(NULL, '', 'Dubrovnik, Croatia', 'Dubrovnik From Above', '', 'Venice and the Balkans'),
(NULL, '', 'Dubrovnik, Croatia', 'Dubrovnik Rooftops', '', 'Venice and the Balkans'),
(NULL, '', 'Kotor, Montenegro', 'Bay of Kotor', '', 'Venice and the Balkans'),
(NULL, '', 'Kotor, Montenegro', 'Bay of Kotor', '', 'Venice and the Balkans'),
(NULL, '', 'Kotor, Montenegro', 'Sunset in the Bay of Kotor', '', 'Venice and the Balkans'),
(NULL, 'acropolis_athens_greece-4.jpg', 'Athens, Greece', 'Greek Flag', '2015-07-20', 'Athens'),
(NULL, 'acropolis_athens_greece-3.jpg', 'Athens, Greece', 'Parthenon', '2015-07-20', 'Athens'),
(NULL, 'athens_acropolis_museum.jpg', 'Athens, Greece', 'Glass Ceiling', '2015-07-20', 'Athens'),
(NULL, 'athens_temple_of_zeus.jpg', 'Athens, Greece', 'The Temple of Olypmian Zeus', '2015-07-20', 'Athens'),
(NULL, 'sunset_street_taverna_athens.jpg', 'Athens, Greece', 'Sunset at the Foot of the Acropolis', '2015-07-20', 'Athens'),
(NULL, 'greece_athens_alleyway-2.jpg', 'Athens, Greece', 'Greek Pathways', '2015-07-20', 'Athens'),
(NULL, 'greece_athens_alleyway-3.jpg', 'Athens, Greece', 'White House, Blue Door', '2015-07-20', 'Athens'),
(NULL, 'athens_protests_2015_neh_yes_eu.jpg', 'Athens, Greece', 'Democracy', '2015-07-20', 'Athens'),
(NULL, 'athens_protests_2015_neh_yes_eu_2.jpg', 'Athens, Greece', 'Police Guarding Parliament', '2015-07-20', 'Athens'),
(NULL, 'greek_protests_oxi_athens.jpg', 'Athens, Greece', 'Protestors', '2015-07-20', 'Athens'),
(NULL, 'greek_protests_oxi_athens_2.jpg', 'Athens, Greece', 'Syntagma Square', '2015-07-20', 'Athens'),
(NULL, 'stairs_and_escalator_athens.jpg', 'Athens, Greece', 'Stairs', '2015-07-20', 'Athens'),
(NULL, 'oia_santorini_sunrise_morning-1.jpg', 'Oia, Greece', 'Churches in Oia', '2015-07-21', 'Santorini'),
(NULL, 'oia_santorini_sunrise_morning-3.jpg', 'Oia, Greece', 'Churches in Oia 2', '2015-07-21', 'Santorini'),
(NULL, 'oia_santorini_sunrise_morning-2.jpg', 'Oia, Greece', 'Sunrise on Santorini', '2015-07-21', 'Santorini'),
(NULL, 'oia_santorini_sunrise_morning-4.jpg', 'Oia, Greece', 'Walkways of Oia', '2015-07-21', 'Santorini'),
(NULL, 'oia_santorini_sunset_night_time.jpg', 'Oia, Greece', 'Oia After Sunset', '2015-07-21', 'Santorini'),
(NULL, 'santorini_skaros_rock-1.jpg', 'Imerovigli, Greece', 'Skaros Rock', '2015-07-21', 'Santorini'),
(NULL, 'santorini_skaros_rock-2.jpg', 'Imerovigli, Greece', 'Imerovigli', '2015-07-21', 'Santorini'),
(NULL, 'akrotiri_santorini_night_lights_stars_astrophotography.jpg', 'Akrotiri, Greece', 'Santorini at Night', '2015-07-21', 'Santorini'),
(NULL, 'akrotiri_santorini_sunset_caldera_beach.jpg', 'Akrotiri, Greece', 'Sunset From the Caldera Beach', '2015-07-21', 'Santorini'),
(NULL, 'akrotiri_santorini_sailboats_sunset_caldera.jpg', 'Akrotiri, Greece', 'Sunset From Akrotiri', '2015-07-21', 'Santorini'),
(NULL, 'akrotiri_santorini_bats_water_caldera.jpg', 'Akrotiri, Greece', 'Boats and Blue Water', '2015-07-21', 'Santorini'),
(NULL, 'santorini_white_beach.jpg', 'Mesa Pigadia, Greece', 'Mesa Pigadia Cliffs', '2015-07-21', 'Santorini'),
(NULL, 'santorini_white_beach_2.jpg', 'Mesa Pigadia, Greece', 'Mesa Pigadia Beach', '2015-07-21', 'Santorini'),
(NULL, 'istanbul_blue_mosque_daytime.jpg', 'Istanbul, Turkey', 'Blue Mosque: Daytime', '', 'Istanbul'),
(NULL, 'istanbul_blue_mosque_sunset_2.jpg', 'Istanbul, Turkey', 'Blue Mosque: Sunset', '', 'Istanbul'),
(NULL, 'istanbul_blue_mosque_night.jpg', 'Istanbul, Turkey', 'Blue Mosque: Night', '', 'Istanbul'),
(NULL, 'istanbul_blue_mosque_inside_interior_architecture_design-1.jpg', 'Istanbul, Turkey', 'Pillar', '', 'Istanbul'),
(NULL, 'istanbul_blue_mosque_inside_interior_architecture_design-2.jpg', 'Istanbul, Turkey', 'Ceiling', '', 'Istanbul'),
(NULL, 'istanbul_haiga_sofia_ayasofia.jpg', 'Istanbul, Turkey', 'Hagia Sofia', '', 'Istanbul'),
(NULL, 'istanbul_cistern_yellow_lights.jpg', 'Istanbul, Turkey', 'Cistern', '', 'Istanbul'),
(NULL, 'istanbul_harem_domed_roof.jpg', 'Istanbul, Turkey', 'Symmetry', '', 'Istanbul'),
(NULL, 'istanbul_street.jpg', 'Istanbul, Turkey', 'Street', '', 'Istanbul'),
(NULL, 'istanbul_corn_stand.jpg', 'Istanbul, Turkey', 'Corn Stand', '', 'Istanbul'),
(NULL, 'istanbul_grand_bazaar_spice_bazaar.jpg', 'Istanbul, Turkey', 'Bazaar', '', 'Istanbul'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Sunset in Anse Marcel', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Blurred Lines', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Iguana', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anguilla', 'Postcard', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anguilla', 'Sailboat', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Saint Martin', 'Seascape', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Saint Martin', 'Evan', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anguilla', 'Sandy Island', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Palm', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Night', '', 'Saint Martin and Anguilla'),
(NULL, '', 'Anse Marcel, Saint Martin', 'Sailboat', '', 'Saint Martin and Anguilla'),
(NULL, 'santa-monica-66-end-of-trail-sign-california.jpg', 'Santa Monica, California', '66', '', 'California'),
(NULL, 'bixby-bridge-big-sur-california.jpg', 'Big Sur, California', 'Bixby Bridge', '', 'California'),
(NULL, 'getty-museum-los-angeles-california (2).jpg', 'Los Angeles, California', 'Modern Architecture', '', 'California'),
(NULL, 'getty-museum-los-angeles-california (3).jpg', 'Los Angeles, California', 'Modern Art', '', 'California'),
(NULL, 'getty-museum-los-angeles-california (4).jpg', 'Los Angeles, California', 'Architecture of the Getty Museum', '', 'California'),
(NULL, 'the-pacific-coast-highway-california.jpg', 'California', 'The Pacific Coast Highway', '', 'California'),
(NULL, 'rocky-landscape-california-coast.jpg', 'California', 'Rocky Coast', '', 'California'),
(NULL, 'hot-air-balloon-heater.jpg', 'Napa Valley, California', 'Burners', '', 'California'),
(NULL, 'aerial-photography-hot-air-balooning (3).jpg', 'Napa Valley, California', 'Foothills', '', 'California'),
(NULL, 'aerial-photography-hot-air-balooning (2).jpg', 'Napa Valley, California', 'Sand Mounds', '', 'California'),
(NULL, 'aerial-view-of-northern-california.jpg', 'Napa Valley, California', 'Leading Lines', '', 'California'),
(NULL, 'grapes-napa-valley-california.jpg', 'Napa Valley, California', 'Grapes', '', 'California'),
(NULL, 'griffith-observatory-architechture-los-angeles-california.jpg', 'Los Angeles, California', 'Griffith Observatory', '', 'California'),
(NULL, 'palm-trees-los-angeles-california (2).jpg', 'Los Angeles, California', 'Tall Palms', '', 'California'),
(NULL, 'star-trails-astrophotography-napa-valley-california.jpg', 'Napa Valley, California', 'Vineyard Star Trails', '', 'California'),
(NULL, 'dock_mist_morning_adirondacks_ny.jpg', 'Inlet, NY', 'Foggy Morning at the Woods Inn', '2014-08-22', 'The Adirondacks'),
(NULL, 'mist-dock-self-portrait-adirondacks-ny.jpg', 'Inlet, NY', 'Self Portrait', '2014-08-22', 'The Adirondacks'),
(NULL, 'misty-morning-adirondacks-ny.jpg', 'Inlet, NY', 'The Fog Rises', '2014-08-22', 'The Adirondacks'),
(NULL, 'adk_Browns_tract_Pond_Milky_Way_Evan_Light.jpg', 'Browns Tract Pond, NY', 'Cloudy With a Chance of Milky Way', '2014-08-16', 'The Adirondacks'),
(NULL, 'adk_Browns_Tract_Pond_milky_way_trees.jpg', 'Browns Tract Pond, NY', 'Milky Way', '2014-08-16', 'The Adirondacks'),
(NULL, 'adk_Browns_tract_Pond_Looking_straight_up.jpg', 'Browns Tract Pond, NY', 'Stars Overhead', '2014-08-16', 'The Adirondacks'),
(NULL, 'adk_Browns_Tract_Pond_stars.jpg', 'Browns Tract Pond, NY', 'Reflections', '2014-08-16', 'The Adirondacks'),
(NULL, 'adk_Raquette_Lake_foggy_morning_dock_and_chair.jpg', 'Raquette Lake, NY', 'Early Morning on Raquette Lake', '2015-08-16', 'The Adirondacks'),
(NULL, 'adk_Raquette_Lake_foggy_morning.jpg', 'Raquette Lake, NY', 'Foggy Morning on Raquette Lake', '2015-08-16', 'The Adirondacks'),
(NULL, 'adk_Browns_Tract_Pond_tree_roots.jpg', 'Browns Tract Pond, NY', 'Roots', '2015-08-16', 'The Adirondacks'),
(NULL, 'adk_Fourth_lake_sunset_galaxy_s5.jpg', 'Inlet, NY', 'Evan', '2015-08-16', 'The Adirondacks'),
(NULL, 'adk_Fourth_lake_sunset_trees_and_lake.jpg', 'Inlet, NY', 'Evan', '2015-08-16', 'The Adirondacks'),
(NULL, 'adk_bald_mountain_fire_tower.jpg', 'Eagle Bay, NY', 'Bald Mountain Fire Tower', '2015-08-16', 'The Adirondacks'),
(NULL, 'nighttime-in-nyc-bokeh-lights.jpg', 'NYC, NY', 'Night Lights', '', 'New York City'),
(NULL, 'sunset-in-central-park-nyc.jpg', 'NYC, NY', 'Central Park Sunset', '', 'New York City'),
(NULL, 'nyc_manhattan_during_sunset.jpg', 'NYC, NY', 'Manhattan: Sunset', '', 'New York City'),
(NULL, 'nyc_manhattan_nighttime.jpg', 'NYC, NY', 'Manhattan: Dusk', '', 'New York City'),
(NULL, 'nyc_one_world_trade.jpg', 'NYC, NY', 'One World Trade', '', 'New York City'),
(NULL, 'audi-r8-tail-light-close-up-nyc-international-auto-show.jpg', 'NYC, NY', 'Audi R8', '', 'New York City'),
(NULL, 'acura-nsx-concept-car-nyc-international-auto-show.jpg', 'NYC, NY', 'Acura NSX', '', 'New York City'),
(NULL, 'red-porsche-nyc-international-auto-show.jpg', 'NYC, NY', 'Porsche Cayman', '', 'New York City'),
(NULL, 'harraford-square-london-england.jpg', 'London, England', 'London Streets', '', 'London, Vienna, and Prague'),
(NULL, 'harraford-sqare-london-england.jpg', 'London, England', 'Harraford Square Houses', '', 'London, Vienna, and Prague'),
(NULL, 'buckingham-palace-gate.jpg', 'London, England', 'Buckingham Palace', '', 'London, Vienna, and Prague'),
(NULL, 'buckingham-palace-gate-macro.jpg', 'London, England', 'Buckingham Gate', '', 'London, Vienna, and Prague'),
(NULL, 'gold-monument-london-england.jpg', 'London, England', 'The Albert Memorial', '', 'London, Vienna, and Prague'),
(NULL, 'aerial-view-prague-czech-republic.jpg', 'Prague, Czech Republic', 'Praha', '', 'London, Vienna, and Prague'),
(NULL, 'Schönbrunn-Palace-vienna-austria (2).jpg', 'Vienna, Austria', 'Schönbrunn Palace', '', 'London, Vienna, and Prague'),
(NULL, 'st.-vitus-cathedral-prague-czech-republic.jpg', 'Prague, Czech Republic', 'St. Vitus Cathedral', '', 'London, Vienna, and Prague'),
(NULL, 'st.-vitus-cathedral-prague-czech-republic.jpg', 'Prague, Czech Republic', 'St. Vitus Cathedral', '', 'London, Vienna, and Prague'),
(NULL, 'tower_bridge_london_UK.jpg', 'London, England', 'Tower Bridge', '', 'London, Vienna, and Prague'),
(NULL, 'minimalistic-ocean-and-sky-blue.jpg', 'Negril, Jamaica', 'Minimalism', '2014-05-03', 'Jamaica'),
(NULL, 'jamaican-sunset-with-boat.jpg', 'Negril, Jamaica', 'Sunset in Negril', '2014-05-13', 'Jamaica'),
(NULL, 'golden-sunset-holding-the-sun.jpg', 'Negril, Jamaica', 'Holding the Sun', '2014-05-13', 'Jamaica'),
(NULL, 'golden-sunset-jamaica (2).jpg', 'Negril, Jamaica', 'Golden Sunset With Trees', '2014-05-13', 'Jamaica'),
(NULL, 'jamaican-beach-performers.jpg', 'Negril, Jamaica', 'Locals', '2014-05-13', 'Jamaica'),
(NULL, 'jamaican-reggae-band.jpg', 'Negril, Jamaica', 'Dr. Hood and the Hoodies', '2014-05-13', 'Jamaica'),
(NULL, 'vibrant-sunset-seen-from-plane.jpg', 'In Flight', 'Sunset From 30,000 feet', '2014-05-13', 'Jamaica'),
(NULL, '', 'L.B.I., NJ', 'Dune', '', 'New Jersey'),
(NULL, '', 'L.B.I., NJ', 'Dune', '', 'New Jersey'),
(NULL, 'Star_Trails_Chatham_NJ.jpg', 'Chatham, NJ', 'Star Trails in Chatham', '2016-03-02', 'New Jersey'),
(NULL, 'star-trails-trees-nj.jpg', 'Chatham, NJ', 'Backyard Star Trails', '2014-05-18', 'New Jersey'),
(NULL, 'blooming-flowers-spring.jpg', 'Chatham, NJ', 'Backyard Star Trails', '2014-06-06', 'New Jersey'),
(NULL, 'fall-park-bench.JPG', 'Chatham, NJ', 'Fall Colors', '2013-10-26', 'New Jersey'),
(NULL, 'nj_bay_head_sunset_dock_long_exposure.jpg', 'Chatham, NJ', 'Fall Colors', '2015-08-16', 'New Jersey'),
(NULL, 'white-flower-on-blue-sky-background.jpg', 'Chatham, NJ', 'Fall Colors', '2014-06-06', 'New Jersey'),
(NULL, 'long-exposure-river-bridge-winter-in-nj.jpg', 'Chatham, NJ', 'Fall Colors', '2015-06-08', 'New Jersey');

INSERT INTO photography_themes(pid, filename, location, description, date_taken, themes_group)
VALUES
(NULL, 'BlueMill-Sunset-Timelapse.mp4', 'Chatham, NJ', 'Blue Mill Rd Sunset', '2017-05-28', 'Timelapse'),
(NULL, 'ADK-BTP-Storm-Rolling-In-Timelapse.mp4', 'Browns Tract Pond, NY', 'Strom Rolling In', '2016-08-19', 'Timelapse'),
(NULL, 'ADK-Fog-Rising-4th-Lake-Timelapse.mp4', 'Inlet, NY', 'Fog Rising', '2016-08-19', 'Timelapse'),
(NULL, 'Barn-Tree-Mendham-Sunset-Timelapse.mp4', 'Mendham, NJ', 'Barn Sunset', '2017-06-01', 'Timelapse'),
(NULL, 'Milky-Way-Timelapse.mp4', 'Browns Tract Pond, NY', 'Milky Way', '2016-08-19', 'Timelapse'),
(NULL, 'ADK-4th-Lake-Sunset-Timelapse.mp4', 'Inlet, NY', 'Sunset Over 4th Lake', '2016-08-09', 'Timelapse'),
(NULL, 'ADK-Rocky-Pt-Sunset-Timelapse.mp4', 'Inlet, NY', 'Rocky Mountain Sunset', '2016-08-19', 'Timelapse'),
(NULL, 'UofM-Diag-Timelapse.mp4', 'Ann Arbor, MI', 'UofM Diag', '2017-02-04', 'Timelapse'),
(NULL, 'Breakers-Sunset-Timelapse.mp4', 'Spring Lake, NJ', 'Sunset From the Breakers', '2017-06-05', 'Timelapse'),
(NULL, 'milky_way_browns_tract_pond_2015_1.jpg', 'Browns Tract Pond, NY', 'Milky Way', '2015-08-17', 'Astro'),
(NULL, 'adk_Browns_Tract_Pond_milky_way_trees.jpg', 'Browns Tract Pond, NY', 'Milky Way Through the Trees', '2015-08-16', 'Astro'),
(NULL, 'adk_Browns_tract_Pond_Looking_straight_up.jpg', 'Browns Tract Pond, NY', 'Looking Up', '2015-08-16', 'Astro'),
(NULL, 'adk_Browns_tract_Pond_Milky_Way_Evan_Light.jpg', 'Browns Tract Pond, NY', 'Cloudy with a Chance of Milky Way', '2015-08-16', 'Astro'),
(NULL, '', 'Josan, Croatia', 'Croatian Milky Way', '', 'Astro'),
(NULL, 'adk_Browns_Tract_Pond_stars.jpg', 'Browns Tract Pond, NY', 'Reflections', '2015-08-16', 'Astro'),
(NULL, 'star-trails-trees-nj.jpg', 'Chatham, NJ', 'Backyard Star Trails', '2014-05-18', 'Astro'),
(NULL, 'star-trails-astrophotography.jpg', 'The Poconos, PA', 'Star Trails', '2014-04-20', 'Astro'),
(NULL, 'chatham-soccer-sports-1.jpg', 'Chatham, NJ', 'Throw In', '2015-06-15', 'Sports'),
(NULL, 'chatham-soccer-sports-2.jpg', 'Chatham, NJ', 'Header', '2015-06-15', 'Sports'),
(NULL, 'hatham-soccer.jpg', 'Chatham, NJ', 'Chatham Soccer', '2015-06-15', 'Sports'),
(NULL, 'longboarding-sports-1.jpg', 'Chatham, NJ', 'Evan', '2015-06-15', 'Sports'),
(NULL, 'penguins-hockey-sports-1.jpg', 'Dunellen, NJ', 'Jersey Penguins', '2015-06-15', 'Sports'),
(NULL, 'special_olympics_nj_2.jpg', 'Princeton, NJ', 'Swimming', '2015-08-18', 'Sports'),
(NULL, 'US_OPEN_TENNIS_Maria_Sharapova_RUS-3.jpg', 'Queens, NY', 'Sharapova From Above', '2015-08-29', 'US Open'),
(NULL, 'Sharapova Four Panel.jpg', 'Queens, NY', 'Sharapova Four Panel', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Maria_Sharapova_RUS-1.jpg', 'Queens, NY', 'Sharapova Black and White', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Rafael_Nadal_ESP-3.jpg', 'Queens, NY', 'Rafael Nadal', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Rafael_Nadal_ESP-1.jpg', 'Queens, NY', 'Rafael Nadal Sprinting', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Gameplay-4.jpg', 'Queens, NY', 'Gameplay From Above', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Blaz_Rola_SLOVENIA-3.jpg', 'Queens, NY', 'Blaž Rola', '2015-08-29', 'US Open'),
(NULL, 'US_OPEN_TENNIS_Ons_Jabeur_TUNISIA-1.jpg', 'Queens, NY', 'Ons Jabeur', '2015-08-29', 'US Open');
